# permissions for end users to view configmappropagations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmappropagation-viewer-role
rules:
- apiGroups:
  - kubegoodies.aliok.github.com
  resources:
  - configmappropagations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubegoodies.aliok.github.com
  resources:
  - configmappropagations/status
  verbs:
  - get
