# permissions for end users to edit configmappropagations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmappropagation-editor-role
rules:
- apiGroups:
  - kubegoodies.aliok.github.com
  resources:
  - configmappropagations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubegoodies.aliok.github.com
  resources:
  - configmappropagations/status
  verbs:
  - get
